### ISSUE TITLE
AncesTree.jar not included

### ISSUE THREAD

**Issue by cott1117** [MathildeFogPerez/ancestree#1]
Hi Mathilde,

I've downloaded the latest version from GitHub but the AncesTree.jar file does not seem to be included. 

Best,
Chris

**Comment by MathildeFogPerez** [comment]
Hi Chris,

sorry to answer you so late, I am on vacation!
You can find AncesTree.jar in the Releases link on the right of the main page. See attached picture. 
Then you click on Assets
![release](https://user-images.githubusercontent.com/10742042/89108177-a765a380-d436-11ea-87c4-449a8b863bb5.png)

best,
Mathilde
