### ISSUE TITLE
Reading IgPhyml output

### ISSUE THREAD

**Issue by jonoave** [MathildeFogPerez/ancestree#2]
Hello,

I ran the analysis using the immcantation pipeline: defining clones, reconstructing germlines, and running IgPhyml using BuildTree. I found the output using alakazam's `readigphyml` to be quite limited and I came across ancestree.

So I reran the Buildtree command, adding the --asr parameter. I loaded the correct db-pass_clone-pass_germ-pass.tsv (ChangeO AIRR file) and the igphyml-pass.tab (igphyml tab file). Then a list of clones popped up, asking me to select one. 
E.g. 219(Nseq=496), 433(Nseq=85)

When I select a clone, and click "Run".
An error pops up: 
There is no clone ID 219 in the change-o airr format file!

I tried this with many other clones in the list, all with the same error.  I opened up the db-pass_clone-pass_germ-pass.tsv file, and under the 'clone ID' column I can find 219 and 433 (many rows of them).

Is there something I'm missing? Thanks and have a nice weekend!

**Comment by MathildeFogPerez** [comment]
Hello!

What version of change-O did you use? Is the clone id column named exaclty as 'clone_id' ?

Mathilde

**Comment by jonoave** [comment]
Hello Mathilda!

Wow I did not expect such a fast response! Thanks for being so responsive!

I installed change-O through conda. 
For CreateGermlines and BuildTree, the version is
1.0.2 2021.01.18

Yes, I checked the db-pass_clone-pass_germ-pass.tsv file. 
I imported the file into excel to verify (the original is on the cluster). 
The column is named exactly 'clone_id', sorted ascendingly in the column number "AX" or column number 50.

Kind regards,
Jun-Hoe

**Comment by MathildeFogPerez** [comment]
This is weird..
Do you mind to send me your AIRR tsv file and igphyml file? Or a part of it, just to try to debug.

**Comment by jonoave** [comment]
Hi Mathilda, 

Thanks for the fast response.
is there a way for me to share the files privately through email or something? i'd rather not post them publicly here. Thanks.

My public email is:
jun [dash] hoe [dot] lee [at] qbic [dot] uni [dash] tuebingen [dot] de

Thanks.

**Comment by MathildeFogPerez** [comment]
It was a problem with the sequence_ids that did not fit between the AIRR file and the Igphyml file.
The sequence_ids contained special character as ":" and Igphyml replaced the ":" by "-" to produce a correct Newick format.
I will add a warning message in Ancestree to warn the user for such discrepancies.
