### ISSUE TITLE
Loading example dnaml and IMGT files and clicking RUN fails to show results

### ISSUE THREAD

**Issue by avilella** [MathildeFogPerez/ancestree#4]
Hi, I've successfully started Ancestree on a Windows machine with JAVA 12 installed. I can load an existing ancestree xml from this repo and use Ancestree to visualize the contents, but I can't get it to work by loading the dnaml+IMGT data.

I've clicked on: `Select the dnaml output file`, selected 
```
https://github.com/MathildeFogPerez/ancestree/blob/master/examples/AncesTree_input_files/dnaml/clone9/Clone9_dnaml_output.txt
```
Then clicked on `Load IMGT info`, selected
```
https://github.com/MathildeFogPerez/ancestree/blob/master/examples/AncesTree_input_files/dnaml/clone9/Clone9_IMGT_data.fasta
```
Clicked `RUN`, but there is no results from it. Any ideas what to try? Thanks in advance

**Comment by MathildeFogPerez** [comment]
Hi,

I just launched AncesTree with JAVA 12 and using the dnaml output files  + IMGT file for clone 9 and it works just fine.
Are you sure you loaded those files?
Did you also try with the files from 'clone_study_case'?

best,
Mathilde
